import Charlantes from 'components/Charlantes'
import Header from 'components/Header'
import PostsListHome from 'components/PostsListHome'
import SectionHome from 'components/SectionHome'
import WhoWeAre from 'components/Whoweare'
import fs from 'fs'
import matter from 'gray-matter'
import Head from 'next/head'

export default function Home({ posts, charlantes }) {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header />

      <SectionHome title={'Who We Are?'}>
        <WhoWeAre />
      </SectionHome>
      <SectionHome className={'charlantes'} title={'Charlantes'}>
        <Charlantes charlantes={charlantes} />
      </SectionHome>
      <SectionHome className={'blog'} title={'Últimos Posts'}>
        <PostsListHome isHome={'true'} posts={posts} />
      </SectionHome>
    </>
  )
}

export async function getStaticProps() {
  const charlantes = getData('charlantes')
    .sort(function () {
      return 0.234 - Math.random()
    })
    .slice(0, 5)

  let posts = getData('posts')

  posts = posts
    .sort((a, b) => {
      return new Date(b.frontmatter.date) - new Date(a.frontmatter.date)
    })
    .slice(0, 3)

  return {
    props: {
      posts,
      charlantes
    }
  }
}

function getData(type) {
  const files = fs.readdirSync(type)
  let items = files.map((fileName) => {
    const slug = fileName.replace('.md', '')
    const readFile = fs.readFileSync(`${type}/${fileName}`, 'utf-8')
    const { data: frontmatter } = matter(readFile)

    return {
      slug,
      frontmatter
    }
  })

  return items
}
