import Charlantes from 'components/Charlantes'
import Header from 'components/Header'
import PostsListHome from 'components/PostsListHome'
import SectionHome from 'components/SectionHome'
import WhoWeAre from 'components/Whoweare'
import fs from 'fs'
import matter from 'gray-matter'
import Head from 'next/head'

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <SectionHome title={'Who We Are?'}>
        <WhoWeAre />
      </SectionHome>
      <SectionHome title={'Charlantes'}>
        <Charlantes />
      </SectionHome>
      <SectionHome title={'Posts'}>
        <PostsListHome posts={posts} />
      </SectionHome>
    </>
  )
}

export async function getStaticProps() {
  const files = fs.readdirSync('posts')
  const posts = files.map((fileName) => {
    const slug = fileName.replace('.md', '')
    const readFile = fs.readFileSync(`posts/${fileName}`, 'utf-8')
    const { data: frontmatter } = matter(readFile)
    console.log(frontmatter)
    return {
      slug,
      frontmatter
    }
  })

  return {
    props: {
      posts
    }
  }
}
